apiVersion: v2
name: devops-assessment
description: A Helm chart for a devops assessment test
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - email: ericalaribeugonna@gmail.com
    name: Eric Alaribe