apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-assessment
  labels:

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-assessment
  template:
    metadata:
      labels:
        app: devops-assessment
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
